# C++ compiler flags
include ~michael.trigoboff/bin/makeflags_g++

asgmt00:			linkedlist.o linkedlist.h

linkedlist.o:	linkedlist.h

.PHONY: x
x:				# clean the directory
				$(info -- cleaning the directory --)
				rm -f *.o asgmt00
